name: Update Data Science Fact Daily
on:
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update today's fact
        run: |
          FACT=$(shuf -n 1 facts.txt | tr -d '"')
          echo "Selected: $FACT"
          
          sed -i '/<!-- KIRAT_DAILY_FACT_START -->/,/<!-- KIRAT_DAILY_FACT_END -->/c\<!-- KIRAT_DAILY_FACT_START -->\n<p align="center"><b>Today'"'"'s Fact:</b> '"$FACT"'</p>\n<!-- KIRAT_DAILY_FACT_END -->' README.md

      - name: Commit & push
        run: |
          git config user.name "FactBot"
          git config user.email "bot@github.com"
          git add README.md
          git commit -m "Updated daily fact ðŸ¤–" || exit 0
          git push
